#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("Bitsie.Shop.Mobile.Resource", IsApplication=true)]

namespace Bitsie.Shop.Mobile
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::ZXing.Mobile.Resource.Id.contentFrame = global::Bitsie.Shop.Mobile.Resource.Id.contentFrame;
			global::ZXing.Mobile.Resource.Layout.zxingscanneractivitylayout = global::Bitsie.Shop.Mobile.Resource.Layout.zxingscanneractivitylayout;
			global::ZXing.Mobile.Resource.Layout.zxingscannerfragmentlayout = global::Bitsie.Shop.Mobile.Resource.Layout.zxingscannerfragmentlayout;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050001
			public const int bitsie_green = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int bitsie_orange = 2131034112;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f060000
			public const int text_size_large = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int text_size_medium = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int text_size_small = 2131099650;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int bitsie_shop_logo = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int chevron = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int dollar_sign = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int nav_border = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int nav_logo = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int numberpad_button = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int orange_border_button = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int orange_border_button_text = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int rounded_corner_green = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int rounded_corner_orange = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int rounded_corner_white = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int splash = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int text_underline = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int white_box_button = 2130837518;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f09000b
			public const int add_gratuity_label = 2131296267;
			
			// aapt resource value: 0x7f09001d
			public const int address = 2131296285;
			
			// aapt resource value: 0x7f09001c
			public const int amount = 2131296284;
			
			// aapt resource value: 0x7f090018
			public const int amountLabel = 2131296280;
			
			// aapt resource value: 0x7f090019
			public const int amountText = 2131296281;
			
			// aapt resource value: 0x7f090021
			public const int contentFrame = 2131296289;
			
			// aapt resource value: 0x7f090012
			public const int continueButton = 2131296274;
			
			// aapt resource value: 0x7f090008
			public const int dollarSign = 2131296264;
			
			// aapt resource value: 0x7f090014
			public const int emailText = 2131296276;
			
			// aapt resource value: 0x7f09001a
			public const int goButton = 2131296282;
			
			// aapt resource value: 0x7f09000e
			public const int gratuity10 = 2131296270;
			
			// aapt resource value: 0x7f09000f
			public const int gratuity15 = 2131296271;
			
			// aapt resource value: 0x7f090010
			public const int gratuity20 = 2131296272;
			
			// aapt resource value: 0x7f090007
			public const int gratuityAmountLabel = 2131296263;
			
			// aapt resource value: 0x7f090009
			public const int gratuityAmountText = 2131296265;
			
			// aapt resource value: 0x7f09000d
			public const int gratuityNone = 2131296269;
			
			// aapt resource value: 0x7f090020
			public const int homeButton = 2131296288;
			
			// aapt resource value: 0x7f090000
			public const int imageView1 = 2131296256;
			
			// aapt resource value: 0x7f090013
			public const int imageViewLogo = 2131296275;
			
			// aapt resource value: 0x7f090017
			public const int loginButton = 2131296279;
			
			// aapt resource value: 0x7f09001b
			public const int name = 2131296283;
			
			// aapt resource value: 0x7f090002
			public const int offlineText = 2131296258;
			
			// aapt resource value: 0x7f09001e
			public const int orderList = 2131296286;
			
			// aapt resource value: 0x7f090016
			public const int passwordText = 2131296278;
			
			// aapt resource value: 0x7f090005
			public const int priceText = 2131296261;
			
			// aapt resource value: 0x7f090003
			public const int qrCodeImage = 2131296259;
			
			// aapt resource value: 0x7f09001f
			public const int receiptText = 2131296287;
			
			// aapt resource value: 0x7f090006
			public const int retryButton = 2131296262;
			
			// aapt resource value: 0x7f09000a
			public const int submitCustomGratuity = 2131296266;
			
			// aapt resource value: 0x7f09000c
			public const int subtotal_label = 2131296268;
			
			// aapt resource value: 0x7f090001
			public const int textView1 = 2131296257;
			
			// aapt resource value: 0x7f090015
			public const int textView2 = 2131296277;
			
			// aapt resource value: 0x7f090004
			public const int totalLabel = 2131296260;
			
			// aapt resource value: 0x7f090011
			public const int totalText = 2131296273;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int BackupPay = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int CustomGratuityDialog = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Gratuity = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Login = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Main = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int OrderRow = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Orders = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Pay = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int Receipt = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int zxingscanneractivitylayout = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int zxingscannerfragmentlayout = 2130903050;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int register = 2130968576;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f070000
			public const int amount = 2131165184;
			
			// aapt resource value: 0x7f070002
			public const int app_name = 2131165186;
			
			// aapt resource value: 0x7f070001
			public const int gratuityAmount = 2131165185;
			
			// aapt resource value: 0x7f070003
			public const int noProvider = 2131165187;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f080000
			public const int Theme_Splash = 2131230720;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
