//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bitsie.Shop.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bitsie.Shop.Web.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An account with this email address could not be found..
        /// </summary>
        internal static string AccountNotFound {
            get {
                return ResourceManager.GetString("AccountNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bid has been canceled..
        /// </summary>
        internal static string BidCanceled {
            get {
                return ResourceManager.GetString("BidCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred while canceling this bid..
        /// </summary>
        internal static string BidCancelError {
            get {
                return ResourceManager.GetString("BidCancelError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bid has been created..
        /// </summary>
        internal static string BidCreated {
            get {
                return ResourceManager.GetString("BidCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company has been approved..
        /// </summary>
        internal static string CompanyApproved {
            get {
                return ResourceManager.GetString("CompanyApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company has been rejected..
        /// </summary>
        internal static string CompanyRejected {
            get {
                return ResourceManager.GetString("CompanyRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company signup successful..
        /// </summary>
        internal static string CompanySignupSuccess {
            get {
                return ResourceManager.GetString("CompanySignupSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company has been updated successfully..
        /// </summary>
        internal static string CompanyUpdated {
            get {
                return ResourceManager.GetString("CompanyUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email/password..
        /// </summary>
        internal static string InvalidCredentials {
            get {
                return ResourceManager.GetString("InvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page has been updated successfully..
        /// </summary>
        internal static string PageUpdated {
            get {
                return ResourceManager.GetString("PageUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password reset email has been sent..
        /// </summary>
        internal static string PasswordResetLinkSent {
            get {
                return ResourceManager.GetString("PasswordResetLinkSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find photo specified..
        /// </summary>
        internal static string PhotoNotFound {
            get {
                return ResourceManager.GetString("PhotoNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find reset key..
        /// </summary>
        internal static string ResetKeyNotFound {
            get {
                return ResourceManager.GetString("ResetKeyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password has been reset successfully. You will now be logged into the site..
        /// </summary>
        internal static string ResetSuccessful {
            get {
                return ResourceManager.GetString("ResetSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trip has been canceled..
        /// </summary>
        internal static string TripCanceled {
            get {
                return ResourceManager.GetString("TripCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bid has been accepted..
        /// </summary>
        internal static string TripConfirmation {
            get {
                return ResourceManager.GetString("TripConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trip has been scheduled..
        /// </summary>
        internal static string TripCreated {
            get {
                return ResourceManager.GetString("TripCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trip could not be found..
        /// </summary>
        internal static string TripNotFound {
            get {
                return ResourceManager.GetString("TripNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User has been created..
        /// </summary>
        internal static string UserCreated {
            get {
                return ResourceManager.GetString("UserCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account has been updated successfully..
        /// </summary>
        internal static string UserUpdated {
            get {
                return ResourceManager.GetString("UserUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle has been created successully..
        /// </summary>
        internal static string VehicleCreated {
            get {
                return ResourceManager.GetString("VehicleCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle has been updated successfully..
        /// </summary>
        internal static string VehicleUpdated {
            get {
                return ResourceManager.GetString("VehicleUpdated", resourceCulture);
            }
        }
    }
}
